const SUCCESSFUL = 'SUCCESSFUL';
const NOT_FOUND = 'NOT_FOUND';
const CREATED = 'CREATED';
const BAD_REQUEST = 'BAD_REQUEST';
const INVALID_VALUE = 'INVALID_VALUE';

module.exports = {
  SUCCESSFUL,
  NOT_FOUND,
  CREATED,
  BAD_REQUEST,
  INVALID_VALUE,
};